= Guided Solution (1 of 1)
:experimental:

== Objectives

* Investigate why the candlepin services are in failed state.
* Solve the candlepin issue in the hands-on lab environment.

== Instructions

Run the following instructions on the `satellite` system with `root` as the user.

.Sample output:
----
[cloud-user@satellite ~]$ sudo su -
[root@satellite ~]#
----

1. Check the `/var/log/messages` log to get some hint . We should see something like the below trace which indicates issues with permissions of files & directories related to candlepin and also in some cases ownership is missing from tomcat.
+
.Sample output:
----
Apr  1 03:38:26 satellite server[6039]: #011java.io.FileNotFoundException: /usr/share/tomcat/conf/server.xml (Permission denied)
Apr  1 03:38:26 satellite server[6039]: 01-Apr-2026 03:38:26.862 WARNING [main] org.apache.catalina.startup.Catalina.parseServerXml Permissions incorrect, read permission is not allowed on the file
Apr  1 03:42:33 satellite server[7775]: #011java.io.FileNotFoundException: /usr/share/tomcat/conf/server.xml (Permission denied)
Apr  1 03:42:33 satellite server[7775]: 01-Apr-2026 03:42:33.887 WARNING [main] org.apache.catalina.startup.Catalina.parseServerXml Permissions incorrect, read permission is not allowed on the file
----

 
 - Check the below files and directories
+

.Sample output:
----
[root@satellite ~]# ls -ld /etc/tomcat
drwxr-xr-x. 4 root root 4096 Mar 22 03:07 /etc/tomcat
^^ Group ownership of tomcat is missing here

[root@satellite ~]# ll /etc/candlepin/candlepin.conf
-rw-r-----. 1 root root 1674 Dec  2 04:50 /etc/candlepin/candlepin.conf
^^ Group ownership of tomcat is missing here

[root@satellite ~]# ls -ld /var/log/candlepin
drw-------. 2 root root 158 Mar 22 03:05 /var/log/candlepin
^^ Permission on others and ownerhsip both are missing here

----

 - To fix it:
+
[source,bash,role=execute]
----
chgrp -R tomcat /etc/tomcat
chgrp tomcat -R /etc/candlepin/
chgrp tomcat /etc/candlepin/candlepin.conf
chown -R tomcat:tomcat /var/log/candlepin
chmod 644 -R /var/log/candlepin
----

2. Check the `/var/log/candlepin/error.log` log to get some further hint . We should see something like the below trace which indicates issues with activemq data corruption.
+
.Sample output:
----
2026-04-01 03:42:58,072 [thread=main] [=, org=, csid=] WARN  org.candlepin.controller.mode.CandlepinModeManager - Candlepin is entering suspend mode. Reason: [ACTIVEMQ] DOWN
2026-04-01 03:42:58,306 [thread=main] [=, org=, csid=] ERROR org.candlepin.async.JobManager - Unexpected exception occurred during initialization
org.candlepin.async.JobException: org.candlepin.messaging.CPMException: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]
----

 - To fix it:
+
[source,bash,role=execute]
----
satellite-maintain service stop
mv /var/lib/candlepin/activemq-artemis{,.old}
satellite-maintain service start
sleep 20 && hammer ping
----


- `hammer ping` should now show all services are ok.
