= Guided Solution (1 of 1)
:experimental:

== Objectives

* Investigate why the candlepin services are in failed state.
* Solve the candlepin issue in the hands-on lab environment.

== Instructions

1. Run the following instructions on the `Red Hat Satellite` system with `root` as the user.
+
.Sample output:
+
[source,subs="verbatim,quotes"]
----
[lab-user@bastion ~]$ **sudo ssh satellite**
[cloud-user@satellite ~]$ **sudo su -**
[root@satellite ~]#
----

2. Check the `/var/log/messages` log to get some hint . You should see something like the below trace which indicates issues with permissions of files & directories related to candlepin and also in some cases ownership is missing from tomcat.
+
.Sample output:
+
[source,subs="verbatim,quotes"]
----
[root@satellite ~]# **grep -i "permission" /var/log/messages**
Apr  1 03:38:26 satellite server[6039]: #011java.io.FileNotFoundException: /usr/share/tomcat/conf/server.xml (Permission denied)
Apr  1 03:38:26 satellite server[6039]: 01-Apr-2026 03:38:26.862 WARNING [main] org.apache.catalina.startup.Catalina.parseServerXml Permissions incorrect, read permission is not allowed on the file
Apr  1 03:42:33 satellite server[7775]: #011java.io.FileNotFoundException: /usr/share/tomcat/conf/server.xml (Permission denied)
Apr  1 03:42:33 satellite server[7775]: 01-Apr-2026 03:42:33.887 WARNING [main] org.apache.catalina.startup.Catalina.parseServerXml Permissions incorrect, read permission is not allowed on the file
----

 
3. Check & verify the permissions & owenership of related files:
+
.Sample output:
+
[source,subs="verbatim,quotes"]
+
----
[root@satellite ~]# **ls -ld /etc/tomcat**
drwxr-xr-x. 4 root root 4096 Mar 22 03:07 /etc/tomcat
^^ Group ownership of tomcat is missing here

[root@satellite ~]# **ll /etc/candlepin/candlepin.conf**
-rw-r-----. 1 root root 1674 Dec  2 04:50 /etc/candlepin/candlepin.conf
^^ Group ownership of tomcat is missing here

[root@satellite ~]# **ls -ld /var/log/candlepin**
drw-------. 2 root root 158 Mar 22 03:05 /var/log/candlepin
^^ Permission on others and ownerhsip both are missing here
----

4. Let's fix the missing files issue and change the group ownership of `/etc/tomcat/` and `/etc/candlepin` followed 
by change of ownership and permissions for `/var/log/candlepin`:
+
[source,subs="verbatim,quotes"]
+
----
[root@satellite ~]# **chgrp -R tomcat /etc/tomcat**
[root@satellite ~]# **chgrp tomcat -R /etc/candlepin/**
[root@satellite ~]# **chown -R tomcat:tomcat /var/log/candlepin**
[root@satellite ~]# **chmod 644 -R /var/log/candlepin**
----

5. Check the `/var/log/candlepin/error.log` log to get some further hint . You should see something like the below trace which indicates issues with activemq data corruption.
+
.Sample output:
+
[source,subs="verbatim,quotes"]
+
----
2026-04-01 03:42:58,072 [thread=main] [=, org=, csid=] WARN  org.candlepin.controller.mode.CandlepinModeManager - Candlepin is entering suspend mode. Reason: [ACTIVEMQ] DOWN
2026-04-01 03:42:58,306 [thread=main] [=, org=, csid=] ERROR org.candlepin.async.JobManager - Unexpected exception occurred during initialization
org.candlepin.async.JobException: org.candlepin.messaging.CPMException: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]
----

6. To fix the file corruption, you would need to first stop the satellite service, then move the corrupted files and then start the services again to regenerate them. Finally we would wait a bit and run hammer ping to check the output:
+
[source,subs="verbatim,quotes"]
+
----
[root@satellite ~]# **satellite-maintain service stop**
[root@satellite ~]# **mv /var/lib/candlepin/activemq-artemis{,.old}**
[root@satellite ~]# **satellite-maintain service start**
[root@satellite ~]# **sleep 20 && hammer ping**
----
+
.The `hammer ping` should now show all services are ok.
+
[source,subs="verbatim,quotes"]
+
----
[root@satellite ~]# **sleep 20 && hammer ping**
database:         
    Status:          ok
    Server Response: Duration: 0ms
cache:            
    servers: 
     1) Status:          ok
        Server Response: Duration: 0ms
candlepin:        
    Status:          ok
    Server Response: Duration: 60ms
candlepin_auth:   
    Status:          ok
    Server Response: Duration: 59ms
candlepin_events: 
    Status:          ok
    message:         0 Processed, 0 Failed
    Server Response: Duration: 0ms
katello_events:   
    Status:          ok
    message:         0 Processed, 0 Failed
    Server Response: Duration: 1ms
pulp3:            
    Status:          ok
    Server Response: Duration: 307ms
pulp3_content:    
    Status:          ok
    Server Response: Duration: 109ms
foreman_tasks:    
    Status:          ok
    Server Response: Duration: 9ms
----
